### ISSUE TITLE
Problems of big knowledge

### ISSUE THREAD

**Issue by VladislavMm** [BlocTheWorker/Inworld-Skyrim-Mod#5]
I remember doing a similar mod back on version 3.5 and faced the problems that the NPCs know too much information. How did you achieve the limitation of their knowledge?)
An example of how I had it -
- Hi, are there any problems?
- Hi, yes, we had a little incident. We were robbed. But we are still ready to offer products for sale. The thieves stole only one thing - an ornament made of pure gold in the shape of a dragon's claw. If you help me get it back, I will be very grateful and will pay for it. You need to go to the Windy Peak if you want to chase the thieves. Do you want to help me?

"And if I don't want to?"
- It's all right, of course. I'll just keep looking for ways to get my claw back. If you need anything, you can contact us about the products in our store.
- Okay, I'll help you
- I'm glad you decided to help me. I have some savings that I'm willing to give you for the return of my claw. If you return it, I will pay you a reward. And if you need any adventure items, you can drop by our store, maybe we already have what you need.

Also more
"Can you tell me where to study magic?"
"I think I have some old spell books lying around somewhere. If you need something more serious, you will have to apply to Winterhold College.
- And how to get to it?
"You can go to Winterhold and walk from there to the Collegium, but I strongly recommend you to be careful. Along the way, you may encounter various dangers.

More humorous questions
"What's your sister's name?"
- My sister's name is Camilla. She often intervenes in my business and offers different ideas on how to improve it or advertise it.
"Do you mind if I start a relationship with her?"
"I have no problem with you starting a relationship with my sister if that's what you both want. However, I would prefer that you continue to visit my store and buy goods from me, even if you are in a relationship with my sister.

Well, here are the questions on which everything collapses XD
- Will I be able to get this decoration in the quest?
- Yes, you will be able to get the Golden Claw decoration as part of the Golden Claw quest. You will need to go to the Blackfold Tower and find Arvel Fleetfoot, who stole the claw. After you find him and return the claw to Lucan, you will receive a reward.

I couldn't limit the level of knowledge of the NPCs in any way, did you manage it? The maximum that I got so that the NPC did not know about modernity, did not answer the question "what is a computer" by type.

I just want to clarify if you have such a problem, without downloading)

**Comment by BlocTheWorker** [comment]
Inworld is using a different system than manually handled ChatGPT. Every character have their own tailored knowledge-base that is feed to them as _facts_ and they also have access to certain _common knowledge_ that they can access. This means, a person in Whiterun can have Whiterun's overall plan/locations as common knowledge and once you add this common knowledge to characters, they will only know their personal facts and that common knowledge. If you don't add anything, they will only know their own personal facts. These facts can be anything - about how they dress, how they should behave etc. Technically speaking, every common knowledge can be added as fact to the NPC line by line too - but if you want to reuse the same fact, then you need to re-add these to each characters. Having common knowledge removes this redundant work. 
But these are about the dynamic facts - or in otherwords, about things that are not part of their training data. You need to limit their knowledge if you suspect that their training data includes anything related to game or quests or whatever you are trying to achieve. Inworld's own system have some premade guardrails to avoid that being happening, as far as I can see, but it doesn't work all the time. So if you feel like players might abuse the certain functionality, you should need to patch it and put guardrails to avoid that being happening.
That being said, knowing too much (because of their training data) can still be a problem. Like modern concepts can still slide through conversation and NPC can start babbling about nuclear fusion and it's specific details. This is quite hard to completely remove given that these data is part of LLM's training and it's hard to drop that bias. Aside from some random hallucinations, I didn't see anything wildly mood-breaking in Inworld's AI so far, that being said, I tend to test it by following the character I'm in so I go _easy_ on it.
If you go to Inworld's page, sign up and start playing around, you can see it yourself.
